#if !canImport(ObjectiveC)
import XCTest

extension AccidentalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccidentalTests = [
        ("testDecodingPlacement", testDecodingPlacement),
        ("testDecodingSimple", testDecodingSimple),
        ("testSimple", testSimple),
    ]
}

extension AccordionRegistrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccordionRegistrationTests = [
        ("testDecoding", testDecoding),
        ("testRoundTrip", testRoundTrip),
    ]
}

extension ArrowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrowTests = [
        ("testAPI", testAPI),
    ]
}

extension ArticulationsTextsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArticulationsTextsTests = [
        ("testColorHex", testColorHex),
    ]
}

extension AttributesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AttributesTests = [
        ("testDecoding", testDecoding),
    ]
}

extension BackupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BackupTests = [
        ("testBackup", testBackup),
    ]
}

extension BarlineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BarlineTests = [
        ("testDecodingSimple", testDecodingSimple),
    ]
}

extension ChordsFretsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChordsFretsTests = [
        ("testFrame", testFrame),
        ("testString", testString),
        ("testStringRoundTrip", testStringRoundTrip),
    ]
}

extension ClefTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClefTests = [
        ("testNoSign", testNoSign),
        ("testOctaveChange", testOctaveChange),
        ("testPercussion", testPercussion),
        ("testSimple", testSimple),
        ("testTAB", testTAB),
    ]
}

extension CreatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CreatorTests = [
        ("testCreatorRoundTrip", testCreatorRoundTrip),
    ]
}

extension DirectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DirectionTests = [
        ("testDecodingDirection_bracket", testDecodingDirection_bracket),
        ("testDecodingDirection_metronome", testDecodingDirection_metronome),
        ("testDecodingDirection_octaveShift", testDecodingDirection_octaveShift),
        ("testDecodingDirection_wedge", testDecodingDirection_wedge),
    ]
}

extension DirectionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DirectionsTests = [
        ("testCoda", testCoda),
        ("testCodaMultiple", testCodaMultiple),
        ("testDashesDirection", testDashesDirection),
        ("testDashesStop", testDashesStop),
        ("testDirectionWedgeAndDynamic", testDirectionWedgeAndDynamic),
        ("testEyeglasses", testEyeglasses),
        ("testFormattedText", testFormattedText),
        ("testHarpPedals", testHarpPedals),
        ("testHarpPedalsDirectionType", testHarpPedalsDirectionType),
        ("testLyricNumberText", testLyricNumberText),
        ("testLyricSyllabic", testLyricSyllabic),
        ("testNoteWithLyric", testNoteWithLyric),
        ("testOtherDynamics", testOtherDynamics),
        ("testPedalChange", testPedalChange),
        ("testPedalDirection", testPedalDirection),
        ("testRehearsal", testRehearsal),
        ("testRehearsalMultiple", testRehearsalMultiple),
        ("testScordatura", testScordatura),
        ("testScordaturaDirectionType", testScordaturaDirectionType),
        ("testSegno", testSegno),
    ]
}

extension EndingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EndingTests = [
        ("testRoundTrip", testRoundTrip),
    ]
}

extension FretTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FretTests = [
        ("testRoundTrip", testRoundTrip),
    ]
}

extension HarmonicTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HarmonicTests = [
        ("testRoundTrip", testRoundTrip),
    ]
}

extension HarmonyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HarmonyTests = [
        ("testDecoding_degree", testDecoding_degree),
        ("testDecoding_degreesAndBass", testDecoding_degreesAndBass),
        ("testDecoding_inversion", testDecoding_inversion),
        ("testDecoding_multipleHarmonyChord", testDecoding_multipleHarmonyChord),
        ("testDecoding_rootOrFunction", testDecoding_rootOrFunction),
    ]
}

extension HelloWorld {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HelloWorld = [
        ("testHelloWorldDecoding", testHelloWorldDecoding),
    ]
}

extension IdentificationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IdentificationTests = [
        ("testDecoding", testDecoding),
        ("testDecodingSimple", testDecodingSimple),
    ]
}

extension KeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyTests = [
        ("testDecodingKeyOctave", testDecodingKeyOctave),
        ("testDecodingNonTraditional", testDecodingNonTraditional),
        ("testDecodingNonTraditionalMixed", testDecodingNonTraditionalMixed),
        ("testDecodingTraditional", testDecodingTraditional),
        ("testDeocdingNonTraditionalWithAccidental", testDeocdingNonTraditionalWithAccidental),
        ("testDeocdingNonTraditionalWithAccidentalSomeMissing", testDeocdingNonTraditionalWithAccidentalSomeMissing),
    ]
}

extension LilyPondTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LilyPondTests = [
        ("testAll", testAll),
    ]
}

extension LyricFontTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LyricFontTests = [
        ("testRoundTrip", testRoundTrip),
    ]
}

extension MIDIDeviceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MIDIDeviceTests = [
        ("testDecoding", testDecoding),
        ("testEncoding", testEncoding),
    ]
}

extension MIDIInstrumentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MIDIInstrumentTests = [
        ("testDecoding", testDecoding),
        ("testEncoding", testEncoding),
    ]
}

extension MeasureNumberingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MeasureNumberingTests = [
        ("testRoundTrip", testRoundTrip),
    ]
}

extension MeasureStyleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MeasureStyleTests = [
        ("testMultipleRest", testMultipleRest),
    ]
}

extension MetronomeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MetronomeTests = [
        ("testDecodingMetronome_beatUnit", testDecodingMetronome_beatUnit),
        ("testDecodingMetronome_noBeatUnitInFirst", testDecodingMetronome_noBeatUnitInFirst),
        ("testDecodingMetronome_perMinute_withDot", testDecodingMetronome_perMinute_withDot),
        ("testDecodingMetronome_perMinute", testDecodingMetronome_perMinute),
    ]
}

extension MidmeasureClefTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MidmeasureClefTests = [
        ("testImplicitMeasureStringNumber", testImplicitMeasureStringNumber),
    ]
}

extension MiscellaneousTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MiscellaneousTests = [
        ("testDecoding", testDecoding),
        ("testMiscellaneousRoundTrip", testMiscellaneousRoundTrip),
    ]
}

extension MusicDataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MusicDataTests = [
        ("testDecodingAttributes", testDecodingAttributes),
        ("testDecodingDivisions", testDecodingDivisions),
    ]
}

extension NotationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NotationsTests = [
        ("testAccidentalMark", testAccidentalMark),
        ("testAccidentalMarkNotation", testAccidentalMarkNotation),
        ("testArpeggiate", testArpeggiate),
        ("testArticulations", testArticulations),
        ("testBreathMarkArticulations", testBreathMarkArticulations),
        ("testDownBowTechnical", testDownBowTechnical),
        ("testFermata", testFermata),
        ("testFermataNoValue", testFermataNoValue),
        ("testFingeringEmpty", testFingeringEmpty),
        ("testFingeringEmptyRoundTrip", testFingeringEmptyRoundTrip),
        ("testFingeringValue", testFingeringValue),
        ("testFingeringValueRoundTrip", testFingeringValueRoundTrip),
        ("testFretTechnical", testFretTechnical),
        ("testMultipleArticulations", testMultipleArticulations),
        ("testNonArpeggiate", testNonArpeggiate),
        ("testOrnamentsNotation", testOrnamentsNotation),
        ("testPluckTechnical", testPluckTechnical),
        ("testSlideNoValue", testSlideNoValue),
        ("testSpiccatoArticulations", testSpiccatoArticulations),
        ("testStaccatoArticulations", testStaccatoArticulations),
        ("testStaccatoNotations", testStaccatoNotations),
        ("testStoppedTechnical", testStoppedTechnical),
        ("testStressArticulations", testStressArticulations),
        ("testStringTechnical", testStringTechnical),
        ("testStrongAccentArticulations", testStrongAccentArticulations),
        ("testTechnical", testTechnical),
        ("testTied", testTied),
        ("testTuplet", testTuplet),
        ("testTurn", testTurn),
        ("testUpBowTechnical", testUpBowTechnical),
    ]
}

extension NoteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NoteTests = [
        ("testBeam", testBeam),
        ("testBeamRoundtrip", testBeamRoundtrip),
        ("testChord", testChord),
        ("testChordRoundTrip", testChordRoundTrip),
        ("testNoteAccidentalDecoding", testNoteAccidentalDecoding),
        ("testNoteAccidentalRoundTrip", testNoteAccidentalRoundTrip),
        ("testNoteDecoding", testNoteDecoding),
        ("testNoteDottedRestDecoding", testNoteDottedRestDecoding),
        ("testNoteDottedRestRoundTrip", testNoteDottedRestRoundTrip),
        ("testNoteheads", testNoteheads),
        ("testNoteheadsRoundTrip", testNoteheadsRoundTrip),
        ("testNoteRoundTrip", testNoteRoundTrip),
        ("testTies", testTies),
        ("testTiesRoundTrip", testTiesRoundTrip),
        ("testTuplet", testTuplet),
        ("testTupletRoundTrip", testTupletRoundTrip),
        ("testUnpitched", testUnpitched),
        ("testUnpitchedRoundTrip", testUnpitchedRoundTrip),
    ]
}

extension OrnamentsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrnamentsTests = [
        ("testDecoding_2", testDecoding_2),
        ("testDecoding", testDecoding),
    ]
}

extension PartListTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PartListTests = [
        ("testScorePartAndPartGroupDecoding", testScorePartAndPartGroupDecoding),
        ("testScorePartDecoding", testScorePartDecoding),
    ]
}

extension PartNameLineBreakTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PartNameLineBreakTests = [
        ("testMeasurePrintNewSystem", testMeasurePrintNewSystem),
    ]
}

extension PartNameTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PartNameTests = [
        ("testDecoding", testDecoding),
        ("testDecodingPartName", testDecodingPartName),
    ]
}

extension PartwiseMeasureTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PartwiseMeasureTests = [
        ("testDecodingAttributes", testDecodingAttributes),
        ("testDecodingBarline", testDecodingBarline),
        ("testDecodingEmpty", testDecodingEmpty),
        ("testDecodingNotes", testDecodingNotes),
    ]
}

extension PartwisePartTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PartwisePartTests = [
        ("testDecoding", testDecoding),
        ("testDecodingSingleMeasure", testDecodingSingleMeasure),
    ]
}

extension PercussionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PercussionTests = [
        ("testOrnamentsEmpty", testOrnamentsEmpty),
    ]
}

extension PickupMeasureChordnamesFiguredBassTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PickupMeasureChordnamesFiguredBassTests = [
        ("testFiguredBass", testFiguredBass),
        ("testFiguredBassDecoding", testFiguredBassDecoding),
        ("testHarmony", testHarmony),
        ("testRoot", testRoot),
    ]
}

extension PitchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PitchTests = [
        ("testHighFQuarterSharpRoundTrip", testHighFQuarterSharpRoundTrip),
        ("testMiddleCRoundTrip", testMiddleCRoundTrip),
    ]
}

extension PitchUnpitchedRestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PitchUnpitchedRestTests = [
        ("testPitch", testPitch),
        ("testRest", testRest),
        ("testUnpitched", testUnpitched),
    ]
}

extension RepeatWithAlternativesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RepeatWithAlternativesTests = [
        ("testBarlineDiscontinue", testBarlineDiscontinue),
    ]
}

extension RestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RestTests = [
        ("testEmpty", testEmpty),
    ]
}

extension ReveTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReveTests = [
        ("testAppearance", testAppearance),
        ("testDefaults", testDefaults),
        ("testEncoding", testEncoding),
        ("testIdentification", testIdentification),
        ("testLyricFonts", testLyricFonts),
        ("testMusicFont", testMusicFont),
        ("testPageLayout", testPageLayout),
        ("testPartListDecoding", testPartListDecoding),
        ("testPrint", testPrint),
        ("testRights", testRights),
        ("testScaling", testScaling),
        ("testStaffLayout", testStaffLayout),
        ("testSupportsAttributeElementTypeValue", testSupportsAttributeElementTypeValue),
        ("testSupportsElementType", testSupportsElementType),
        ("testSystemLayout2", testSystemLayout2),
        ("testSystemLayout", testSystemLayout),
        ("testWordFont", testWordFont),
    ]
}

extension ScoreInstrumentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScoreInstrumentTests = [
        ("testDecoding", testDecoding),
    ]
}

extension ScorePartTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScorePartTests = [
        ("testComplex", testComplex),
        ("testDecoding_complex", testDecoding_complex),
        ("testDecoding", testDecoding),
        ("testRoundTrip", testRoundTrip),
    ]
}

extension ScoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScoreTests = [
        ("testAll", testAll),
    ]
}

extension SimpleRepeatTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SimpleRepeatTests = [
        ("testBarlineRepeatBackward", testBarlineRepeatBackward),
    ]
}

extension StabatMaterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StabatMaterTests = [
        ("testDynamics", testDynamics),
        ("testDynamicsDirection", testDynamicsDirection),
        ("testDynamicsDirectionType", testDynamicsDirectionType),
        ("testDynamicsMultipleInDirectionType", testDynamicsMultipleInDirectionType),
        ("testWordsDirection", testWordsDirection),
        ("testWordsDirectionType", testWordsDirectionType),
        ("testWordsMultipleInDirectionType", testWordsMultipleInDirectionType),
    ]
}

extension StaffNoteStylesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StaffNoteStylesTests = [
        ("testMeasureStyles", testMeasureStyles),
        ("testMeasureStylesAttributes", testMeasureStylesAttributes),
        ("testSlash", testSlash),
    ]
}

extension SystemLayoutTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SystemLayoutTests = [
        ("testDecoding", testDecoding),
    ]
}

extension TimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimeTests = [
        ("testDecodingCommon", testDecodingCommon),
        ("testDecodingMeasured", testDecodingMeasured),
    ]
}

extension TraversalConversionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TraversalConversionTests = [
        ("testHelloWorldRoundTrip", testHelloWorldRoundTrip),
    ]
}

extension TupletsTremoloTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TupletsTremoloTest = [
        ("testTremolo", testTremolo),
        ("testTupletsTremolo", testTupletsTremolo),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccidentalTests.__allTests__AccidentalTests),
        testCase(AccordionRegistrationTests.__allTests__AccordionRegistrationTests),
        testCase(ArrowTests.__allTests__ArrowTests),
        testCase(ArticulationsTextsTests.__allTests__ArticulationsTextsTests),
        testCase(AttributesTests.__allTests__AttributesTests),
        testCase(BackupTests.__allTests__BackupTests),
        testCase(BarlineTests.__allTests__BarlineTests),
        testCase(ChordsFretsTests.__allTests__ChordsFretsTests),
        testCase(ClefTests.__allTests__ClefTests),
        testCase(CreatorTests.__allTests__CreatorTests),
        testCase(DirectionTests.__allTests__DirectionTests),
        testCase(DirectionsTests.__allTests__DirectionsTests),
        testCase(EndingTests.__allTests__EndingTests),
        testCase(FretTests.__allTests__FretTests),
        testCase(HarmonicTests.__allTests__HarmonicTests),
        testCase(HarmonyTests.__allTests__HarmonyTests),
        testCase(HelloWorld.__allTests__HelloWorld),
        testCase(IdentificationTests.__allTests__IdentificationTests),
        testCase(KeyTests.__allTests__KeyTests),
        testCase(LilyPondTests.__allTests__LilyPondTests),
        testCase(LyricFontTests.__allTests__LyricFontTests),
        testCase(MIDIDeviceTests.__allTests__MIDIDeviceTests),
        testCase(MIDIInstrumentTests.__allTests__MIDIInstrumentTests),
        testCase(MeasureNumberingTests.__allTests__MeasureNumberingTests),
        testCase(MeasureStyleTests.__allTests__MeasureStyleTests),
        testCase(MetronomeTests.__allTests__MetronomeTests),
        testCase(MidmeasureClefTests.__allTests__MidmeasureClefTests),
        testCase(MiscellaneousTests.__allTests__MiscellaneousTests),
        testCase(MusicDataTests.__allTests__MusicDataTests),
        testCase(NotationsTests.__allTests__NotationsTests),
        testCase(NoteTests.__allTests__NoteTests),
        testCase(OrnamentsTests.__allTests__OrnamentsTests),
        testCase(PartListTests.__allTests__PartListTests),
        testCase(PartNameLineBreakTests.__allTests__PartNameLineBreakTests),
        testCase(PartNameTests.__allTests__PartNameTests),
        testCase(PartwiseMeasureTests.__allTests__PartwiseMeasureTests),
        testCase(PartwisePartTests.__allTests__PartwisePartTests),
        testCase(PercussionTests.__allTests__PercussionTests),
        testCase(PickupMeasureChordnamesFiguredBassTests.__allTests__PickupMeasureChordnamesFiguredBassTests),
        testCase(PitchTests.__allTests__PitchTests),
        testCase(PitchUnpitchedRestTests.__allTests__PitchUnpitchedRestTests),
        testCase(RepeatWithAlternativesTests.__allTests__RepeatWithAlternativesTests),
        testCase(RestTests.__allTests__RestTests),
        testCase(ReveTests.__allTests__ReveTests),
        testCase(ScoreInstrumentTests.__allTests__ScoreInstrumentTests),
        testCase(ScorePartTests.__allTests__ScorePartTests),
        testCase(ScoreTests.__allTests__ScoreTests),
        testCase(SimpleRepeatTests.__allTests__SimpleRepeatTests),
        testCase(StabatMaterTests.__allTests__StabatMaterTests),
        testCase(StaffNoteStylesTests.__allTests__StaffNoteStylesTests),
        testCase(SystemLayoutTests.__allTests__SystemLayoutTests),
        testCase(TimeTests.__allTests__TimeTests),
        testCase(TraversalConversionTests.__allTests__TraversalConversionTests),
        testCase(TupletsTremoloTest.__allTests__TupletsTremoloTest),
    ]
}
#endif
