#if !canImport(ObjectiveC)
import XCTest

extension AccidentalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccidentalTests = [
        ("testDecodingSimple", testDecodingSimple),
    ]
}

extension AttributesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AttributesTests = [
        ("testDecoding", testDecoding),
    ]
}

extension BackupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BackupTests = [
        ("testBackup", testBackup),
    ]
}

extension BarlineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BarlineTests = [
        ("testDecodingSimple", testDecodingSimple),
    ]
}

extension ClefTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClefTests = [
        ("testNoSign", testNoSign),
        ("testOctaveChange", testOctaveChange),
        ("testPercussion", testPercussion),
        ("testSimple", testSimple),
        ("testTAB", testTAB),
    ]
}

extension IdentificationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IdentificationTests = [
        ("testDecoding", testDecoding),
    ]
}

extension KeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyTests = [
        ("testDecodingTraditional", testDecodingTraditional),
    ]
}

extension MeasureStyleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MeasureStyleTests = [
        ("testMultipleRest", testMultipleRest),
    ]
}

extension MiscellaneousTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MiscellaneousTests = [
        ("testDecoding", testDecoding),
        ("testMiscellaneousRoundTrip", testMiscellaneousRoundTrip),
    ]
}

extension MusicDataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MusicDataTests = [
        ("testDecodingAttributes", testDecodingAttributes),
        ("testDecodingDivisions", testDecodingDivisions),
    ]
}

extension NotationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NotationsTests = [
        ("testFermata", testFermata),
        ("testMultipleArticulations", testMultipleArticulations),
    ]
}

extension NoteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NoteTests = [
        ("testNoteAccidentalDecoding", testNoteAccidentalDecoding),
        ("testNoteDecoding", testNoteDecoding),
    ]
}

extension PartListTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PartListTests = [
        ("testScorePartAndPartGroupDecoding", testScorePartAndPartGroupDecoding),
        ("testScorePartDecoding", testScorePartDecoding),
    ]
}

extension PartNameTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PartNameTests = [
        ("testDecoding", testDecoding),
    ]
}

extension PartwiseMeasureTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PartwiseMeasureTests = [
        ("testDecodingAttributes", testDecodingAttributes),
        ("testDecodingEmpty", testDecodingEmpty),
        ("testDecodingNotes", testDecodingNotes),
    ]
}

extension PartwisePartTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PartwisePartTests = [
        ("testDecoding", testDecoding),
        ("testDecodingSingleMeasure", testDecodingSingleMeasure),
    ]
}

extension Partwise_01_Pitches {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Partwise_01_Pitches = [
        ("test_01_Pitches", test_01_Pitches),
    ]
}

extension Partwise_02_Rests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Partwise_02_Rests = [
        ("test_02_Rests", test_02_Rests),
    ]
}

extension Partwise_03_Rhythm {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Partwise_03_Rhythm = [
        ("test_03_Rhythm", test_03_Rhythm),
    ]
}

extension Partwise_12_Clefs {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Partwise_12_Clefs = [
        ("test_12_Clefs", test_12_Clefs),
    ]
}

extension Partwise_14_StaffDetails {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Partwise_14_StaffDetails = [
        ("test_14_StaffDetails", test_14_StaffDetails),
    ]
}

extension Partwise_23_Tuplets {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Partwise_23_Tuplets = [
        ("test_23_Tuplets", test_23_Tuplets),
    ]
}

extension PitchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PitchTests = [
        ("testHighFQuarterSharpRoundTrip", testHighFQuarterSharpRoundTrip),
        ("testMiddleCRoundTrip", testMiddleCRoundTrip),
    ]
}

extension PitchUnpitchedRestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PitchUnpitchedRestTests = [
        ("testPitch", testPitch),
        ("testRest", testRest),
        ("testUnpitched", testUnpitched),
    ]
}

extension RestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RestTests = [
        ("testEmpty", testEmpty),
    ]
}

extension ScorePartTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScorePartTests = [
        ("testDecoding", testDecoding),
    ]
}

extension TimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimeTests = [
        ("testDecodingCommon", testDecodingCommon),
        ("testDecodingMeasured", testDecodingMeasured),
    ]
}

extension Timewise_01_Pitches {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Timewise_01_Pitches = [
        ("test_01_Pitches", test_01_Pitches),
    ]
}

extension Timewise_02_Rests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Timewise_02_Rests = [
        ("test_02_Rests", test_02_Rests),
    ]
}

extension Timewise_03_Rhythm {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Timewise_03_Rhythm = [
        ("test_03_Rhythm", test_03_Rhythm),
    ]
}

extension Timewise_12_Clefs {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Timewise_12_Clefs = [
        ("test_12_Clefs", test_12_Clefs),
    ]
}

extension Timewise_14_StaffDetails {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Timewise_14_StaffDetails = [
        ("test_14_StaffDetails", test_14_StaffDetails),
    ]
}

extension Timewise_23_Tuplets {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Timewise_23_Tuplets = [
        ("test_23_Tuplets", test_23_Tuplets),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccidentalTests.__allTests__AccidentalTests),
        testCase(AttributesTests.__allTests__AttributesTests),
        testCase(BackupTests.__allTests__BackupTests),
        testCase(BarlineTests.__allTests__BarlineTests),
        testCase(ClefTests.__allTests__ClefTests),
        testCase(IdentificationTests.__allTests__IdentificationTests),
        testCase(KeyTests.__allTests__KeyTests),
        testCase(MeasureStyleTests.__allTests__MeasureStyleTests),
        testCase(MiscellaneousTests.__allTests__MiscellaneousTests),
        testCase(MusicDataTests.__allTests__MusicDataTests),
        testCase(NotationsTests.__allTests__NotationsTests),
        testCase(NoteTests.__allTests__NoteTests),
        testCase(PartListTests.__allTests__PartListTests),
        testCase(PartNameTests.__allTests__PartNameTests),
        testCase(PartwiseMeasureTests.__allTests__PartwiseMeasureTests),
        testCase(PartwisePartTests.__allTests__PartwisePartTests),
        testCase(Partwise_01_Pitches.__allTests__Partwise_01_Pitches),
        testCase(Partwise_02_Rests.__allTests__Partwise_02_Rests),
        testCase(Partwise_03_Rhythm.__allTests__Partwise_03_Rhythm),
        testCase(Partwise_12_Clefs.__allTests__Partwise_12_Clefs),
        testCase(Partwise_14_StaffDetails.__allTests__Partwise_14_StaffDetails),
        testCase(Partwise_23_Tuplets.__allTests__Partwise_23_Tuplets),
        testCase(PitchTests.__allTests__PitchTests),
        testCase(PitchUnpitchedRestTests.__allTests__PitchUnpitchedRestTests),
        testCase(RestTests.__allTests__RestTests),
        testCase(ScorePartTests.__allTests__ScorePartTests),
        testCase(TimeTests.__allTests__TimeTests),
        testCase(Timewise_01_Pitches.__allTests__Timewise_01_Pitches),
        testCase(Timewise_02_Rests.__allTests__Timewise_02_Rests),
        testCase(Timewise_03_Rhythm.__allTests__Timewise_03_Rhythm),
        testCase(Timewise_12_Clefs.__allTests__Timewise_12_Clefs),
        testCase(Timewise_14_StaffDetails.__allTests__Timewise_14_StaffDetails),
        testCase(Timewise_23_Tuplets.__allTests__Timewise_23_Tuplets),
    ]
}
#endif
