//
//  PartwisePartTests.swift
//  MusicXMLTests
//
//  Created by James Bean on 8/4/19.
//

import XCTest
import XMLCoder
@testable import MusicXML

class PartwisePartTests: XCTestCase {

    func testDecodingSingleMeasure() throws {
        let xml = """
        <part id="P1">
            <measure number="1">
            <attributes>
              <divisions>1</divisions>
              <key>
                <fifths>0</fifths>
                <mode>major</mode>
              </key>
              <time symbol="common">
                <beats>4</beats>
                <beat-type>4</beat-type>
              </time>
              <clef>
                <sign>G</sign>
                <line>2</line>
              </clef>
            </attributes>
            <note>
              <pitch>
                <step>G</step>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
          </measure>
        </part>
        """
        let decoded = try XMLDecoder().decode(Partwise.Part.self, from: xml.data(using: .utf8)!)
        let expected = Partwise.Part(
            id: "P1",
            measures: [
                Partwise.Measure(
                    number: 1,
                    musicData: [
                        .attributes(
                            Attributes(
                                divisions: 1,
                                keys: [Key(fifths: 0, mode: .major)],
                                times: [Time(4, 4, symbol: .common)],
                                clefs: [Clef(sign: .g, line: 2)]
                            )
                        ),
                        .note(
                            Note(
                                kind: .normal(
                                    Note.Normal(
                                        pitchUnpitchedOrRest: .pitch(Pitch(step: .g, octave: 2)),
                                        duration: 1
                                    )
                                ),
                                voice: "1",
                                type: NoteType( .quarter)
                            )
                        ),
                        .note(
                            Note(
                                kind: .normal(
                                    Note.Normal(
                                        pitchUnpitchedOrRest: .pitch(Pitch(step: .a, octave: 2)),
                                        duration: 1
                                    )
                                ),
                                voice: "1",
                                type: NoteType( .quarter)
                            )
                        ),
                        .note(
                            Note(
                                kind: .normal(
                                    Note.Normal(
                                        pitchUnpitchedOrRest: .pitch(Pitch(step: .b, octave: 2)),
                                        duration: 1
                                    )
                                ),
                                voice: "1",
                                type: NoteType( .quarter)
                            )
                        ),
                        .note(
                            Note(
                                kind: .normal(
                                    Note.Normal(
                                        pitchUnpitchedOrRest: .pitch(Pitch(step: .c, octave: 3)),
                                        duration: 1
                                    )
                                ),
                                voice: "1",
                                type: NoteType( .quarter)
                            )
                        )
                    ]
                )
            ]
        )
        XCTAssertEqual(decoded, expected)
    }

    func testDecoding() throws {
        let xml = """
        <part id="P1">
            <measure number="1">
            <attributes>
              <divisions>1</divisions>
              <key>
                <fifths>0</fifths>
                <mode>major</mode>
              </key>
              <time symbol="common">
                <beats>4</beats>
                <beat-type>4</beat-type>
              </time>
              <clef>
                <sign>G</sign>
                <line>2</line>
              </clef>
            </attributes>
            <note>
              <pitch>
                <step>G</step>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="2">
            <note>
              <pitch>
                <step>D</step>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>E</step>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>F</step>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>G</step>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="3">
            <note>
              <pitch>
                <step>A</step>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>D</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="4">
            <note>
              <pitch>
                <step>E</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>F</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>G</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="5">
            <note>
              <pitch>
                <step>B</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>D</step>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>E</step>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="6">
            <note>
              <pitch>
                <step>F</step>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>G</step>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="7">
            <note>
              <pitch>
                <step>C</step>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>D</step>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>E</step>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>F</step>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="8">
            <note>
              <pitch>
                <step>G</step>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <octave>7</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="9">
            <note>
              <pitch>
                <step>G</step>
                <alter>1</alter>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <alter>1</alter>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <alter>1</alter>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="10">
            <note>
              <pitch>
                <step>D</step>
                <alter>1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>E</step>
                <alter>1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>F</step>
                <alter>1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>G</step>
                <alter>1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="11">
            <note>
              <pitch>
                <step>A</step>
                <alter>1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <alter>1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>D</step>
                <alter>1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="12">
            <note>
              <pitch>
                <step>E</step>
                <alter>1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>F</step>
                <alter>1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>G</step>
                <alter>1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <alter>1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="13">
            <note>
              <pitch>
                <step>B</step>
                <alter>1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>D</step>
                <alter>1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>E</step>
                <alter>1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="14">
            <note>
              <pitch>
                <step>F</step>
                <alter>1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>G</step>
                <alter>1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <alter>1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <alter>1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="15">
            <note>
              <pitch>
                <step>C</step>
                <alter>1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>D</step>
                <alter>1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>E</step>
                <alter>1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>F</step>
                <alter>1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="16">
            <note>
              <pitch>
                <step>G</step>
                <alter>1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <alter>1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <alter>1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>1</alter>
                <octave>7</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="17">
            <note>
              <pitch>
                <step>G</step>
                <alter>-1</alter>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <alter>-1</alter>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <alter>-1</alter>
                <octave>2</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>-1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="18">
            <note>
              <pitch>
                <step>D</step>
                <alter>-1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>E</step>
                <alter>-1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>F</step>
                <alter>-1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>G</step>
                <alter>-1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="19">
            <note>
              <pitch>
                <step>A</step>
                <alter>-1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <alter>-1</alter>
                <octave>3</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>-1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>D</step>
                <alter>-1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="20">
            <note>
              <pitch>
                <step>E</step>
                <alter>-1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>F</step>
                <alter>-1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>G</step>
                <alter>-1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <alter>-1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="21">
            <note>
              <pitch>
                <step>B</step>
                <alter>-1</alter>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>-1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>D</step>
                <alter>-1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>E</step>
                <alter>-1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="22">
            <note>
              <pitch>
                <step>F</step>
                <alter>-1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>G</step>
                <alter>-1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <alter>-1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <alter>-1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="23">
            <note>
              <pitch>
                <step>C</step>
                <alter>-1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>D</step>
                <alter>-1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>E</step>
                <alter>-1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>F</step>
                <alter>-1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="24">
            <note>
              <pitch>
                <step>G</step>
                <alter>-1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <alter>-1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>B</step>
                <alter>-1</alter>
                <octave>6</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>-1</alter>
                <octave>7</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="25">
            <note>
              <pitch>
                <step>E</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>natural</accidental>
            </note>
            <note>
              <pitch>
                <step>F</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>natural</accidental>
            </note>
            <note>
              <pitch>
                <step>G</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>natural</accidental>
            </note>
            <note>
              <pitch>
                <step>A</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>natural</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="26">
            <note>
              <pitch>
                <step>B</step>
                <octave>4</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>natural</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>natural</accidental>
            </note>
            <note>
              <pitch>
                <step>D</step>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>natural</accidental>
            </note>
            <note>
              <pitch>
                <step>E</step>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>natural</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="27">
            <note>
              <pitch>
                <step>C</step>
                <alter>2</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>double-sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>-2</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>flat-flat</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
          </measure>
          <!--=======================================================-->
          <measure number="28">
            <note>
              <pitch>
                <step>C</step>
                <alter>1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental>sharp</accidental>
            </note>
            <note>
              <pitch>
                <step>C</step>
                <alter>1</alter>
                <octave>5</octave>
              </pitch>
              <duration>1</duration>
              <voice>1</voice>
              <type>quarter</type>
              <accidental editorial="yes">sharp</accidental>
            </note>
            <barline location="right">
              <bar-style>light-heavy</bar-style>
            </barline>
          </measure>
        </part>
        """
        let decoded = try XMLDecoder().decode(Partwise.Part.self, from: xml.data(using: .utf8)!)
        #warning("Add assertion to PatwisePartTests.testDecoding()")
    }
}
